export const FLIGHT_MEDIA_AUDIO_EVENT_KEYS = [
  "ops.dock_success",
  "ops.dock_reject",
  "ops.undock_success",
  "ops.refuel_success",
  "admin.market_tick_success",
  "admin.market_tick_fail",
  "admin.logs_refresh",
  "comms.local_send",
  "comms.relay_queued",
  "comms.relay_delivered",
  "admin.user_update_success",
  "admin.user_update_fail",
  "flight.destination_selected",
  "flight.jump_initiated",
  "flight.jump_arrived",
  "trade.loop_step_complete",
  "flight.engine_loop_start",
  "flight.traffic_flyby",
  "flight.mode_confirm",
  "scanner.ping",
  "scanner.contact_selected",
  "scanner.contact_class_star",
  "scanner.contact_class_planet",
  "scanner.contact_class_station",
  "scanner.contact_class_ship",
  "ops.docking_request_accept",
  "ops.docking_request_reject",
  "flight.docked_bay_ambience_start",
  "ops.undock_launch",
  "collision.glancing_hit",
  "collision.critical_hit",
  "collision.warning_alarm",
  "ops.crash_recovery_start",
  "ops.crash_recovery_complete",
  "chart.open",
  "chart.sync_success",
  "chart.sync_fail",
  "chart.waypoint_lock",
  "chart.waypoint_unlock",
  "chart.layer_toggle_on",
  "chart.layer_toggle_off",
  "nav.target_acquired",
  "nav.target_locked",
  "nav.invalid_action",
  "nav.approach_ready",
  "dock.transit_enter",
  "dock.transit_exit",
  "flight.throttle_accel",
  "flight.throttle_decel",
  "flight.motion_loop",
  "jump.charge_start",
  "jump.transit_peak",
  "jump.hyperspace_charge_start",
  "jump.hyperspace_transit_peak",
  "jump.exit",
  "jump.exit_stabilize",
  "jump.hyperspace_exit",
  "jump.hyperspace_exit_stabilize",
] as const;

export type FlightMediaAudioEventKey = (typeof FLIGHT_MEDIA_AUDIO_EVENT_KEYS)[number];

const FLIGHT_MEDIA_AUDIO_SFX_BY_EVENT = Object.fromEntries(
  FLIGHT_MEDIA_AUDIO_EVENT_KEYS.map((eventName) => [
    eventName,
    `/audio/sfx/${eventName.replaceAll(".", "-")}.wav`,
  ]),
) as Record<FlightMediaAudioEventKey, string>;

export const FLIGHT_MEDIA_AUDIO_DIAGNOSTIC_URI = "/audio/sfx/diagnostic-tone.wav";

export const resolveFlightMediaAudioSfxUri = (
  eventName: string,
): string | null => FLIGHT_MEDIA_AUDIO_SFX_BY_EVENT[eventName as FlightMediaAudioEventKey] ?? null;
